source "https://rubygems.org"
ruby "2.7.2"

gem "sinatra"
gem "thin"
gem "dotenv"
gem "redis"
gem "httparty"
gem "foreman"
gem "text"
gem "concurrent-ruby"
gem "rest-client"
gem "redis-semaphore"
gem "sanitize"
